```{r knitsetup, echo=FALSE, results='hide', warning=FALSE, message=FALSE, cache=FALSE}
opts_knit$set(base.dir='./', fig.path='', out.format='md')
opts_chunk$set(prompt=TRUE, comment='', results='markup')
# See yihui.name/knitr/options for more Knitr options.
##### Put other setup R code here

require(ggplot2)
require(granova)
require(granovaGG)
require(Matching)
require(MatchIt)
require(party)
require(PSAgraphics)
require(rbounds)
require(rpart)
require(multilevelPSA)
require(tree)
require(TriMatch)
require(PSAboot)

data(lalonde, package='Matching')
data(lindner, package='PSAgraphics')

```

Estimating Propensity Scores
========================================================

#### Logistic Regression

```{r}
lalonde.formu <- treat ~ age+ educ + black + hisp + married + nodegr + re74 + re75
lalonde.glm <- glm(lalonde.formu, family=binomial, data=lalonde)

summary(lalonde.glm)
```


```{r}
ps <- fitted(lalonde.glm)  # Propensity scores
Y  <- lalonde$re78  # Dependent variable, real earnings in 1978
Tr <- lalonde$treat # Treatment indicator
```

#### Classification Trees


