# Matching {#chapter-matching}

::: {.rmdtip}
**match**  
*verb*  
1. correspond or cause to correspond in some essential respect; make or be harmonious.  
2. be equal to (something) in quality or strength.
:::


```{r}
lalonde.glm <- glm(lalonde.formu, family=binomial, data=lalonde)
ps <- fitted(lalonde.glm)  # Propensity scores
Y  <- lalonde$re78  # Dependent variable, real earnings in 1978
Tr <- lalonde$treat # Treatment indicator

```


```{r introduction-logistic, eval = FALSE, echo=FALSE, fig.height=4, fig.cap='Propensity Scores from Logistic Regression with Sample of Matched Pairs'}
lalonde.lr <- glm(lalonde.formu, family=binomial, data=lalonde)
lalonde$ps <- fitted(lalonde.lr)
lalonde.match <- Match(Y=lalonde$re78, Tr=lalonde$treat, X=lalonde$ps, M=1);
lalonde.match.df <- data.frame(treated.ps=lalonde[lalonde.match$index.treated,]$ps,
						       control.ps=lalonde[lalonde.match$index.control,]$ps,
							   treated.y=1, control.y=0)
lalonde.match.df <- lalonde.match.df[order(lalonde.match.df$control.ps),]
rows <- (1:nrow(lalonde.match.df) - 1) %% floor(nrow(lalonde.match.df) / 5) == 0
ggplot(lalonde, aes(x=ps, y=treat)) + geom_point(alpha=0.5) +
	stat_smooth(method="glm", method.args=list(family="binomial"), se=FALSE) +
	xlim(c(0,1)) + xlab('Propensity Score') + ylab('Treatment') +
	geom_segment(data=lalonde.match.df[rows,], 
				 aes(x=treated.ps, xend=control.ps, y=treated.y, yend=control.y),
				 color='purple')
```

```{r}
## Matching
# one-to-one matching with replacement (the "M=1" option).
# Estimating the treatment effect on the treated (default is ATT).
rr.att <- Match(Y = Y, 
				Tr = Tr, 
				X = ps,
				M = 1,
				estimand='ATT')
summary(rr.att) # The default estimate is ATT here
ls(rr.att)

rr.ate <- Match(Y=Y, Tr=Tr, X=ps, M=1, estimand='ATE')
summary(rr.ate)
ls(rr.ate)
```



```{r}
rr2 <- Match(Y = Y,
			 Tr = Tr,
			 X = ps,
			 M = 1, 
			 ties = TRUE, 
			 replace = TRUE,
			 estimand = 'ATT')
summary(rr2) # The default estimate is ATT here
length(unique(rr2$index.control))
ls(rr2)
```



```{r}
## Using the Matchit package
matchit.out <- matchit(lalonde.formu, data=lalonde)
summary(matchit.out)

# Same as above but calculate average treatment effect
rr.ate <- Match(Y=Y, Tr=Tr, X=ps, M=1, ties=FALSE, replace=FALSE, estimand='ATE')
summary(rr.ate) # Here the estimate is ATE

## Genetic Matching
rr.gen <- GenMatch(Tr=Tr, X=ps, 
				   BalanceMatrix=lalonde[,all.vars(lalonde.formu)[-1]],
				   estimand='ATE', M=1, pop.size=16)
rr.gen.mout <- Match(Y=Y, Tr=Tr, X=ps, estimand='ATE', Weight.matrix=rr.gen)
summary(rr.gen.mout)

## Partial exact matching
rr2 <- Matchby(Y=Y, Tr=Tr, X=ps, by=factor(lalonde$nodegr))
summary(rr2)

## Partial exact matching on two covariates
rr3 <- Matchby(Y=Y, Tr=Tr, X=ps, by=lalonde[,c('nodegr','married')])
summary(rr3)
```


